'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {create}=require('../lib/item-operation');
const {coordinatorFixture,repositoryFixture}=require('./fixtures/item-protocol');
const request=()=>({schemaVersion:1,opId:'op-1',kind:'issue',itemCode:'I',source:{loc:'L',container:'C'},expected:{itemVersion:3,containerVersion:2}});
function setup(){const durable={commands:new Map(),owner:null},repository=repositoryFixture();const service=()=>create({repository,coordinator:coordinatorFixture(durable),enabled:true,authenticate:async()=>({id:'server-user',roles:['operator','service']})});return {durable,repository,service};}
test('two handler instances share claim; duplicate opId produces one effect and query has none',async()=>{const f=setup(),a=f.service(),b=f.service();await Promise.all([a.post({},request()),b.post({},request())]);assert.equal(f.repository.writes,1);assert.equal((await b.get({},'op-1')).phase,'APPLIED');assert.equal(f.repository.state.items[0].container,'');assert.equal(f.repository.logs[0].operator,'server-user');await assert.rejects(b.post({},{...request(),reason:'changed'}),/PAYLOAD_CONFLICT/);});
test('different concurrent operations on same item allow one business effect',async()=>{const f=setup();await Promise.allSettled([f.service().post({},request()),f.service().post({},{...request(),opId:'op-2'})]);assert.equal(f.repository.writes,1);});
test('log creation timeout leaves persistent barrier across fresh instances',async()=>{const f=setup();f.repository.faults.prepare=true;const r=await f.service().post({},request());assert.equal(r.phase,'REPAIR_REQUIRED');assert.equal(f.repository.writes,0);await assert.rejects(f.service().post({},{...request(),opId:'other'}),/BARRIER/);assert.equal((await f.service().get({},'op-1')).phase,'REPAIR_REQUIRED');});
test('entity before after timeout is not proof original write ended; no retry apply',async()=>{const f=setup();f.repository.faults.apply=true;await f.service().post({},request());f.repository.faults.apply=false;const result=await f.service().recover({},'op-1');assert.equal(result.phase,'REPAIR_REQUIRED');assert.equal(f.repository.writes,1);assert.equal(f.durable.owner,'op-1');});
test('entity succeeded log finish failed: fresh recovery only finalizes log',async()=>{const f=setup();f.repository.faults.finish=true;await f.service().post({},request());f.repository.faults.finish=false;assert.equal((await f.service().recover({},'op-1')).phase,'APPLIED');assert.equal(f.repository.writes,1);assert.equal(f.durable.owner,null);});
test('missing coordination or auth fail before repository side effects',async()=>{const repository=repositoryFixture();const a=create({repository,enabled:true,authenticate:async()=>({id:'user',roles:['operator']})});await assert.rejects(a.post({},request()),/COORDINATION/);const b=create({repository,enabled:false,authenticate:async()=>null});await assert.rejects(b.post({},request()),/UNAUTHENTICATED/);assert.equal(repository.writes,0);});
test('operation visibility is owner/admin/service only and missing roles gets 403',async()=>{const f=setup();await f.service().post({},request());const as=actor=>create({repository:f.repository,coordinator:coordinatorFixture(f.durable),enabled:true,authenticate:async()=>actor});for(const actor of [{id:'stranger',roles:['operator']},{id:'server-user',roles:[]},{id:'server-user'}]){await assert.rejects(as(actor).get({},'op-1'),e=>e.status===403);}await assert.rejects(as({id:'stranger',roles:['operator']}).post({},request()),e=>e.status===403);await assert.rejects(as({id:'server-user'}).recover({},'op-1'),e=>e.status===403);assert.equal((await as({id:'admin',roles:['admin']}).get({},'op-1')).phase,'APPLIED');});
test('schema failure rejects without effect, unknown GET does not claim never executed',async()=>{const f=setup();f.repository.faults.schema=true;assert.equal((await f.service().post({},request())).phase,'REJECTED');assert.equal(f.repository.writes,0);assert.equal((await f.service().get({},'missing')).phase,'UNKNOWN');});
