'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {parseHTML}=require('linkedom'),UI=require('../lib/item-ui');
function setup(persistence=null,mediaDevices=null){const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8'),{document}=parseHTML(html);let n=0,writes=0;const state={locations:[{code:'SAME',status:'active',desc:'location'},{code:'L-A',status:'active'}],containers:[{code:'C-A',loc:'L-A',status:'active',version:2}],items:[{code:'SAME',name:'item',status:'pending',version:0},{code:'I-P',name:'part',status:'pending',version:0}]};const page=UI.mount({document,mediaDevices,getState:()=>state,getPersistence:()=>persistence,getCommands:async()=>[],id:()=>String(++n)});return {document,state,page,writes};}
test('DOM query typed prefix selects item and bare collision lists candidates without write',()=>{const {document:d,state}=setup(),before=JSON.stringify(state);d.getElementById('itmSearch').value='SAME';d.getElementById('itmSearchBtn').click();assert.match(d.getElementById('itmResults').textContent,/多个候选/);assert.equal(d.getElementById('itmResults').querySelectorAll('button').length,2);d.getElementById('itmSearch').value='ITM:SAME';d.getElementById('itmSearchBtn').click();assert.match(d.getElementById('itmResults').textContent,/数量：1/);assert.equal(JSON.stringify(state),before);});
test('DOM draft save/restore and double confirm persist exactly one command',async()=>{let draft=null,calls=0;const persistence={async saveDraft(id,value){draft={key:'itmDraft:'+id,value:structuredClone(value)};},async recover(){return {drafts:draft?[draft]:[],commands:[]};},async enqueue(){calls++;}};const {document:d,page}=setup(persistence);await page.accept('LOC:L-A');await page.accept('CTN:C-A');d.getElementById('itmDraftSave').click();await new Promise(r=>setImmediate(r));page.scan.reset();d.getElementById('itmDraftRestore').click();await new Promise(r=>setImmediate(r));assert.equal(page.scan.row().values.length,2);await page.accept('ITM:I-P');d.getElementById('itmConfirm').click();d.getElementById('itmConfirm').click();await new Promise(r=>setImmediate(r));assert.equal(calls,1);assert.match(d.getElementById('itmStatus').textContent,/不代表业务完成/);});
test('DOM IDB enqueue failure does not display completion and leaves retry available',async()=>{const {document:d,page}=setup({async enqueue(){throw Error('IDB写失败');}});for(const text of ['LOC:L-A','CTN:C-A','ITM:I-P'])await page.accept(text);d.getElementById('itmConfirm').click();await new Promise(r=>setImmediate(r));assert.match(d.getElementById('itmStatus').textContent,/IDB写失败/);assert.equal(page.scan.row().locked,false);assert.equal(d.getElementById('itmConfirm').disabled,false);});
test('late getUserMedia after stop releases stream without opening video',async()=>{let resolve,stopped=0;const {document:d,page}=setup(null,{getUserMedia:()=>new Promise(r=>resolve=r)});d.getElementById('itmCamera').click();page.stopCamera();resolve({getTracks:()=>[{stop(){stopped++;}}]});await new Promise(r=>setImmediate(r));assert.equal(stopped,1);assert.equal(d.getElementById('itmVideo').style.display,'none');});
test('video play rejection releases camera and clears srcObject',async()=>{let stopped=0;const {document:d}=setup(null,{async getUserMedia(){return {getTracks:()=>[{stop(){stopped++;}}]};}});d.getElementById('itmVideo').play=async()=>{throw Error('play denied');};d.getElementById('itmCamera').click();await new Promise(r=>setImmediate(r));assert.equal(stopped,1);assert.equal(d.getElementById('itmVideo').srcObject,null);assert.match(d.getElementById('itmStatus').textContent,/播放失败/);});
test('admin activation UI queues controlled command without mutating legacy location',async()=>{let queued;const {document:d,state}=setup({async enqueue(r){queued=r;}});state.locations.push({code:'LEGACY',status:'unknown'});d.getElementById('itmAdminLoc').value='LEGACY';d.getElementById('itmActivateLoc').click();await new Promise(r=>setImmediate(r));assert.equal(queued.kind,'activateLocation');assert.equal(queued.expected.locationStatus,'unknown');assert.equal(state.locations.at(-1).status,'unknown');});
test('query scan cannot fill operation row; row table resolves APPLIED by opId',async()=>{const {document:d,page,state}=setup();const before=page.scan.snapshot();page.queryScan('ITM:I-P');assert.deepEqual(page.scan.snapshot(),before);assert.match(d.getElementById('itmResults').textContent,/数量：1/);for(const code of ['LOC:L-A','CTN:C-A','ITM:I-P'])await page.accept(code);const q=page.scan.lock();state.itemOperations=[{code:q.opId,phase:'APPLIED'}];page.render();assert.match(d.getElementById('itmRowTable').textContent,/已完成/);assert.equal(page.scan.row().locked,true);});
test('DOM location drilldown to container then item works via actual clicks',()=>{const {document:d,state}=setup();state.items[1]={...state.items[1],status:'in_stock',container:'C-A'};d.getElementById('itmSearch').value='LOC:L-A';d.getElementById('itmSearchBtn').click();d.getElementById('itmResults').querySelector('button').click();const buttons=[...d.getElementById('itmResults').querySelectorAll('button')];buttons.find(b=>b.textContent.includes('I-P')).click();assert.match(d.getElementById('itmResults').textContent,/C-A → L-A/);});
