'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {parseHTML}=require('linkedom'),UI=require('../lib/item-ui');
function setup(persistence=null,scanCamera=null){const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8'),{document}=parseHTML(html);let n=0,writes=0;const state={locations:[{code:'SAME',status:'active',desc:'location'},{code:'L-A',status:'active'}],containers:[{code:'C-A',loc:'L-A',status:'active',version:2}],items:[{code:'SAME',name:'item',status:'pending',version:0},{code:'I-P',name:'part',status:'pending',version:0}]};const page=UI.mount({document,scanCamera,getState:()=>state,getPersistence:()=>persistence,getCommands:async()=>[],id:()=>String(++n)});return {document,state,page,writes};}
function fakeCam(){return {opened:0,closed:0,lastOpts:null,isOpen:()=>false,async open(o){this.opened++;this.lastOpts=o;},close(){this.closed++;}};}
test('DOM query typed prefix selects item and bare collision lists candidates without write',()=>{const {document:d,state}=setup(),before=JSON.stringify(state);d.getElementById('itmSearch').value='SAME';d.getElementById('itmSearchBtn').click();assert.match(d.getElementById('itmResults').textContent,/多个候选/);assert.equal(d.getElementById('itmResults').querySelectorAll('button').length,2);d.getElementById('itmSearch').value='ITM:SAME';d.getElementById('itmSearchBtn').click();assert.match(d.getElementById('itmResults').textContent,/数量：1/);assert.equal(JSON.stringify(state),before);});
test('DOM draft save/restore and double confirm persist exactly one command',async()=>{let draft=null,calls=0;const persistence={async saveDraft(id,value){draft={key:'itmDraft:'+id,value:structuredClone(value)};},async recover(){return {drafts:draft?[draft]:[],commands:[]};},async enqueue(){calls++;}};const {document:d,page}=setup(persistence);await page.accept('LOC:L-A');await page.accept('CTN:C-A');d.getElementById('itmDraftSave').click();await new Promise(r=>setImmediate(r));page.scan.reset();d.getElementById('itmDraftRestore').click();await new Promise(r=>setImmediate(r));assert.equal(page.scan.row().values.length,2);await page.accept('ITM:I-P');d.getElementById('itmConfirm').click();d.getElementById('itmConfirm').click();await new Promise(r=>setImmediate(r));assert.equal(calls,1);assert.match(d.getElementById('itmStatus').textContent,/不代表业务完成/);});
test('DOM IDB enqueue failure does not display completion and leaves retry available',async()=>{const {document:d,page}=setup({async enqueue(){throw Error('IDB写失败');}});for(const text of ['LOC:L-A','CTN:C-A','ITM:I-P'])await page.accept(text);d.getElementById('itmConfirm').click();await new Promise(r=>setImmediate(r));assert.match(d.getElementById('itmStatus').textContent,/IDB写失败/);assert.equal(page.scan.row().locked,false);assert.equal(d.getElementById('itmConfirm').disabled,false);});
test('work camera opens shared ScanCamera with row token; confirm card fills current step',async()=>{const cam=fakeCam();const {document:d,page}=setup(null,cam);d.getElementById('itmCamera').click();await new Promise(r=>setImmediate(r));assert.equal(cam.opened,1);assert.equal(typeof cam.lastOpts.captureToken,'function');const token=cam.lastOpts.captureToken();cam.lastOpts.onConfirm('LOC:L-A',token);await new Promise(r=>setImmediate(r));assert.equal(page.scan.row().values.length,1);assert.equal(page.scan.row().values[0].code,'L-A');page.stopCamera();assert.equal(cam.closed,1);});
test('query camera confirm fills query box only after user confirms',async()=>{const cam=fakeCam();const {document:d}=setup(null,cam);d.getElementById('itmSearchCamera').click();await new Promise(r=>setImmediate(r));assert.equal(cam.opened,1);cam.lastOpts.onConfirm('ITM:I-P');await new Promise(r=>setImmediate(r));assert.equal(d.getElementById('itmSearch').value,'ITM:I-P');assert.match(d.getElementById('itmResults').textContent,/part/);});
test('work describe rejects wrong-type code before filling',async()=>{const cam=fakeCam();const {document:d}=setup(null,cam);d.getElementById('itmCamera').click();await new Promise(r=>setImmediate(r));const verdict=cam.lastOpts.describe({text:'ITM:I-P',format:'条形码'});assert.equal(verdict.ok,false);assert.match(verdict.text,/库位/);});
test('admin activation UI queues controlled command without mutating legacy location',async()=>{let queued;const {document:d,state}=setup({async enqueue(r){queued=r;}});state.locations.push({code:'LEGACY',status:'unknown'});d.getElementById('itmAdminLoc').value='LEGACY';d.getElementById('itmActivateLoc').click();await new Promise(r=>setImmediate(r));assert.equal(queued.kind,'activateLocation');assert.equal(queued.expected.locationStatus,'unknown');assert.equal(state.locations.at(-1).status,'unknown');});
test('query scan cannot fill operation row; row table resolves APPLIED by opId',async()=>{const {document:d,page,state}=setup();const before=page.scan.snapshot();page.queryScan('ITM:I-P');assert.deepEqual(page.scan.snapshot(),before);assert.match(d.getElementById('itmResults').textContent,/数量：1/);for(const code of ['LOC:L-A','CTN:C-A','ITM:I-P'])await page.accept(code);const q=page.scan.lock();state.itemOperations=[{code:q.opId,phase:'APPLIED'}];page.render();assert.match(d.getElementById('itmRowTable').textContent,/已完成/);assert.equal(page.scan.row().locked,true);});
test('query camera error stays in visible query status and does not overwrite work status',async()=>{const {document:d}=setup();const work=d.getElementById('itmStatus').textContent;d.getElementById('itmSearchCamera').click();await new Promise(r=>setImmediate(r));assert.match(d.getElementById('itmSearchStatus').textContent,/查询失败|不可用/);assert.equal(d.getElementById('itmStatus').textContent,work);});
test('work UI translates kind, renders dynamic steps and mobile table labels',async()=>{const {document:d,page}=setup();assert.match(d.getElementById('itmStep').textContent,/入库.*目标库位/s);await page.accept('LOC:L-A');assert.match(d.getElementById('itmStep').textContent,/✓ 1 目标库位：L-A.*目标容器/s);const cells=[...d.getElementById('itmRowTable').querySelectorAll('td')];assert.deepEqual(cells.map(x=>x.getAttribute('data-th')),['行','库位','容器','物品','操作','状态']);assert.match(d.getElementById('itmRowTable').textContent,/入库/);assert.doesNotMatch(d.getElementById('itmStep').textContent,/行 \d+；/);});
test('search results are Chinese cards with translated state and separate status',()=>{const {document:d}=setup();d.getElementById('itmSearch').value='part';d.getElementById('itmSearchBtn').click();assert.equal(d.getElementById('itmResults').querySelectorAll('.itm-result-card').length,1);assert.match(d.getElementById('itmResults').textContent,/物品.*待入库/s);assert.match(d.getElementById('itmSearchStatus').textContent,/找到 1 条/);});
test('six operation types keep original sequences with distinct Chinese step guides',()=>{const {document:d,page}=setup();for(const [kind,count,label] of [['receive',3,'入库物品'],['issue',3,'出库物品'],['transfer',5,'目标容器'],['moveContainer',3,'待移动容器'],['placeContainer',2,'待定位容器'],['verifyLegacy',3,'旧物品']]){page.scan.add(kind);page.render();assert.equal(d.getElementById('itmStep').querySelectorAll('li').length,count);assert.match(d.getElementById('itmStep').textContent,new RegExp(label));assert.equal(d.getElementById('itmConfirm').disabled,true);}});
test('pending cards never auto-submit and preserve original command for explicit actions',async()=>{const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8'),{document:d}=parseHTML(html);const command={id:'uuid-long-original-command',status:'pending',request:{kind:'receive',itemCode:'I-P',target:{loc:'L-A',container:'C-A'}}};let submitted=0,queried=0;const page=UI.mount({document:d,getState:()=>({}),id:()=> 'id',getPersistence:()=>null,getCommands:async()=>[command],getClient:()=>({submit:async c=>{assert.equal(c,command);submitted++;return {phase:'APPLIED'};},query:async c=>{assert.equal(c,command);queried++;return {phase:'PREPARED'};}})});await page.pending();assert.equal(submitted,0);assert.equal(queried,0);const card=d.getElementById('itmPending').querySelector('article');assert.match(card.textContent,/入库 · 待提交/);assert.match(card.querySelector('.itm-meta').textContent,/uuid-long-original-command/);card.querySelector('button').click();await new Promise(r=>setImmediate(r));assert.equal(submitted,1);assert.equal(queried,0);d.getElementById('itmPending').querySelectorAll('button')[1].click();await new Promise(r=>setImmediate(r));assert.equal(queried,1);assert.match(d.getElementById('itmStatus').textContent,/已准备，待确认/);});
test('query missing codes and detail errors stay local without mutating state or drafts',()=>{const {document:d,page,state}=setup();const before=JSON.stringify(state),draft=page.scan.snapshot(),work=d.getElementById('itmStatus').textContent;page.queryScan('ITM:missing');assert.match(d.getElementById('itmSearchStatus').textContent,/未找到编码/);page.detail('items','missing');assert.match(d.getElementById('itmSearchStatus').textContent,/查询失败/);assert.equal(d.getElementById('itmStatus').textContent,work);assert.equal(JSON.stringify(state),before);assert.deepEqual(page.scan.snapshot(),draft);});
test('DOM location drilldown to container then item works via actual clicks',()=>{const {document:d,state}=setup();state.items[1]={...state.items[1],status:'in_stock',container:'C-A'};d.getElementById('itmSearch').value='LOC:L-A';d.getElementById('itmSearchBtn').click();d.getElementById('itmResults').querySelector('button').click();const buttons=[...d.getElementById('itmResults').querySelectorAll('button')];buttons.find(b=>b.textContent.includes('I-P')).click();assert.match(d.getElementById('itmResults').textContent,/C-A → L-A/);});
const tickN=async(n=6)=>{for(let i=0;i<n;i++)await new Promise(r=>setImmediate(r));};
function setupGuided(){const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8'),{document}=parseHTML(html);let n=0;const state={locations:[{code:'L-OLD',status:'unknown'},{code:'L-A',status:'active'}],containers:[{code:'C-OLD',loc:'L-A',status:'unknown',version:0}],items:[]};let queued=null,submitted=0;const persistence={async enqueue(r){queued=r;},async saveDraft(){},async recover(){return{drafts:[],commands:[]}}};const client={async submit(c){submitted++;if(c.request.kind==='activateLocation')state.locations[0].status='active';if(c.request.kind==='activateContainer')state.containers[0].status='active';return {phase:'APPLIED',code:c.id};}};const page=UI.mount({document,getState:()=>state,getPersistence:()=>persistence,getCommands:async()=>queued?[{id:queued.opId,op:'itemOperation',request:queued}]:[],getClient:()=>client,id:()=>'guided-'+(++n)});return {document,state,page,get queued(){return queued},get submitted(){return submitted}};}
test('guided activate: unknown LOC blocks fill, action button enables and retries into step',async()=>{
 const s=setupGuided();const d=s.document,page=s.page;
 d.getElementById('itmCode').value='LOC:L-OLD';d.getElementById('itmScanBtn').click();await tickN();
 assert.match(d.getElementById('itmStatus').textContent,/未启用/);assert.equal(page.scan.row().values.length,0);
 const action=d.getElementById('itmStatus').querySelector('button');assert.ok(action,'应提供现场核实启用按钮');
 action.click();await tickN(12);
 assert.equal(s.queued&&s.queued.kind,'activateLocation');assert.equal(s.submitted,1);
 assert.deepEqual(page.scan.row().values.map(v=>v.code),['L-OLD'],'APPLIED后自动重试填入原步骤');
});
test('guided activate: unknown container uses current row LOC as target and resumes',async()=>{
 const s=setupGuided();const d=s.document,page=s.page;
 await page.accept('LOC:L-A');
 d.getElementById('itmCode').value='CTN:C-OLD';d.getElementById('itmScanBtn').click();await tickN();
 const action=d.getElementById('itmStatus').querySelector('button');assert.ok(action,'容器未启用应提供引导按钮');
 action.click();await tickN(12);
 assert.equal(s.queued&&s.queued.kind,'activateContainer');assert.equal(s.queued&&s.queued.target.loc,'L-A');assert.equal(s.submitted,1);
 assert.deepEqual(page.scan.row().values.map(v=>v.code),['L-A','C-OLD']);
});
